name = "system load"
targets = ["linux"]
#disabled = true

script = "load.sh"
arguments = "$load_normal_cmd"

delay = "1m"
timeout = "8s"

### Default values

[[default]]
name = "load_normal_cmd"
value = "/root/backup.sh"

[[default]]
name = "load_margin"
value = 0

### Checks

[[check]]
desc = "heavy system load"
if = "LOAD > (CPU_COUNT+load_margin) && PROG_DETECTED == 0"
classes = ["warning"]
needed_failures = 2
